import sys


def exit_success():
    print("#########################   SUCCESS   #######################")
    sys.exit(0)


def exit_failure():
    print("#########################   FAILURE   #######################")
    sys.exit(1)
